services:
  api1: &api
    image: ghcr.io/pedrosakuma/rinha-backend-2026-gpu-bruteforce:latest
    platform: linux/amd64
    command:
      - --serve
      - --backend
      - vulkan
      - --listen
      - 0.0.0.0:8080
      - --skip-validate
      - --cpu-adapter-reference-limit
      - "100000"
      - --require-resource-files
      - --references-path
      - /app/resources/references.json.gz
      - --mcc-risk-path
      - /app/resources/mcc_risk.json
      - --normalization-path
      - /app/resources/normalization.json
    deploy:
      resources:
        limits:
          cpus: "0.49"
          memory: "160M"

  api2:
    <<: *api

  lb:
    image: ghcr.io/pedrosakuma/rinha-backend-2026-gpu-bruteforce-lb:latest
    platform: linux/amd64
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.02"
          memory: "30M"
